create database manageStudent;
use manageStudent;

CREATE TABLE STUDENT (
    STUDENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100)
);

CREATE TABLE COURSE (
    COURSE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100)
);

CREATE TABLE STUDENT_COURSE (
    STUDENT_ID BIGINT,
    COURSE_ID BIGINT,
    PRIMARY KEY (STUDENT_ID, COURSE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);